/* eslint-disable vue/multi-word-component-names */
<template>
    <div class="my-4">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgba(0, 0, 0, 0) none repeat scroll 0% 0%; display: block; shape-rendering: auto;" width="32px" height="32px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
            <circle cx="50" cy="50" fill="none" stroke="#e5e7eb" stroke-width="16" r="32" stroke-dasharray="150.79644737231007 52.26548245743669">
                <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
            </circle>
        <!-- [ldio] generated by https://loading.io/ -->
        </svg>
    </div>
</template>